### ISSUE TITLE
`abideCreate` fails under Windows if path contains space

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/grunt-i18n-abide#47]
Hi

If gettext utilities for Windows were installed into directory, which has spaces (and it's quite typical situation, since most part of software under Windows installed in `Program Files`), `abideCreate` task will fail with following error:

![xvbkm5](https://cloud.githubusercontent.com/assets/4460311/7903691/7d3413e2-07ec-11e5-94d1-ad5f6432fed9.png)

Under some nasty characters hiddes following message:

```
"C:\Program" isn't internal or external
command, executable program or file
```

(translation can be a bit inaccurate)

Reason for such behaviour is quite simple — space in path.

Command need to be executed in following format to prevent such behavior:

```
"C:\Program Files\gettext-iconv\msginit.exe" --no-translator --input locale\templates\LC_MESSAGE
S\messages.pot --output locale\en_US\LC_MESSAGES\messages.po -l en_US
```

Note wrapping quotes around path to executable `msginit.exe`.

**Comment by muffinresearch** [comment]
Thanks for the report. I've got a patch together that should fix this.  It'll be up shortly.

**Comment by muffinresearch** [comment]
0.0.16 has been released and pushed to npm - that should hopefully solve the problem.

**Comment by ArmorDarks** [comment]
thanks a lot!

**Comment by ArmorDarks** [comment]
Uh, seems that issue remains unresolved...

![dmon5o](https://cloud.githubusercontent.com/assets/4460311/7932901/1d5450d4-0924-11e5-8df6-410ad5e98545.png)

Under glyphs said `Syntaxis error in file name, directory name or volume label`

I guess the reason are single quotes.

If I run manually command with single quotes, it yeild same error:

```
'C:\Program Files\gettext-iconv\msginit.exe' --no-translator --input 'locale\templates\LC_MESSAG
ES\messages.pot' --output 'locale\en_US\LC_MESSAGES\messages.po' -l en_US
Синтаксическая ошибка в имени файла, имени папки или метке тома.
```

With double quotes it works and generating po as expected, but in same time throws another error:

```
"C:\Program Files\gettext-iconv\msginit.exe" --no-translator --input "locale\templates\LC_MESSAG
ES\messages.pot" --output "locale\en_US\LC_MESSAGES\messages.po" -l en_US
C:\Program Files\gettext-iconv\msginit.exe: /home/m/build-gettext-windows/out-shared-64/lib/gettext/project-id subprocess failed: No such file or directory
Created locale\en_US\LC_MESSAGES\messages.po.
```

**Comment by muffinresearch** [comment]
Seems like something windows specific relating to quoting - there was a definite bug that the escaping fixes - but, it would appear that the lib I used isn't doing the right thing for windows. I'm trying to find what the concrete rules are for shell escaping in windows so I can provide a better fix.

**Comment by ArmorDarks** [comment]
Well, the thing is definately single quotes, since they can't be used in Windows cmd bash, except few cases.

http://stackoverflow.com/questions/24173825/what-does-single-quote-do-in-windows-batch-files

I don't know what up with that `subprocess failed`, since command creates file as expected. It's even unclear which exactly process fails.

**Comment by muffinresearch** [comment]
@ArmorDarks  I've looked into this and it seems completely non-trivial. Even using code that's supposed to work x-platform I'm getting various errors with msginit.exe. Also I'm lacking info on exactly what the rules are for windows.

Have you tried running this under bash.exe ? http://win-bash.sourceforge.net/  - whilst that won't be ideal - if that worked I'd be tempted to say that's a dependency of this working on windows.

**Comment by ArmorDarks** [comment]
Hm, what exactly winBash should provide for correct work? I'm using [cmder](http://gooseberrycreative.com/cmder/) + msysgit, so most part of UNIX utilities are accesable via cmder, they are injected into Win enviroment, so I even can run Shell scripts with cmder, but it definately doesn't help.

Maybe subproccess fails somehow related to binaries, which are most used for gettext under Windows: http://mlocati.github.io/gettext-iconv-windows/

However, as I've already mentioned, even with those fails commands actually works. It just needs double quotes instead of single ones in passed commands, that's all.

**Comment by muffinresearch** [comment]
I don't have enough windows knowledge to fix this (I spent a few hours trying to incorporate something that would work in all cases and I'm still having issues on windows). I'd be happy to review a patch for this if someone who understands the windows case can provide something that will work without breaking things for unix.

**Comment by ArmorDarks** [comment]
Sadly enough, that issue still persists.

I wonder, can be fixed at least issue with single quotes under Windows?

In Windows everywhere should be used double quotes, otherwise even `abideExtract` will fail.

This will work:

```
"J:\Work\Kotsu\node_modules\grunt-i18n-abide\node_modules\.bin\jsxgettext" "source/layouts/_layout.nj"  -o "source\locales\_templates\messages.pot" --language Jinja
```

This wont:

```
// will report syntactical error in filename or path

'J:\Work\Kotsu\node_modules\grunt-i18n-abide\node_modules\.bin\jsxgettext' 'source/layouts/_layout.nj'  -o 'source\locales\_templates\messages.pot' --language Jinja
```

**Comment by ArmorDarks** [comment]
I also wonder — if `jsxgettext` would have API instead of only CLI, will it make things easier?

**Comment by muffinresearch** [comment]
@ArmorDarks if you have ideas and want to knock up a patch I'll happily review it.
